Fix build when net-snmp does not support DES
Build fails when usmDESPrivProtocol is not defined, it is the
case for instance on el9.

nm_snmp.c: In function 'nm_snmp_open':
nm_snmp.c:801:44: error: 'usmDESPrivProtocol' undeclared (first use in this function); did you mean 'usmAESPrivProtocol'?
  801 |         nm_cmu_session.securityPrivProto = usmDESPrivProtocol;
      |                                            ^~~~~~~~~~~~~~~~~~
      |                                            usmAESPrivProtocol
nm_snmp.c:801:44: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [<builtin>: nm_snmp.o] Error 1